k22100_顔の検出、加工、保存
2023AIT-OOP2-G14/11_ImageProcessing pull request #21
Opened 2024-01-06 22:31 UTC by niwa100

## やったこと
顔検出、枠を追加、保存処理部分の追加

## やらないこと
無し

## できるようになること（ユーザ目線）
画像の顔部分を検出し、枠をつけることができる

## 動作確認

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2024-01-07 09:15 UTC, Nibosi0501 commented
修正してほしいところがあります。確認してください。

2024-01-07 09:21 UTC, Nibosi0501 requested changes
２点、画像のパスを書き換えてほしいです。
修正お願いします。

2024-01-07 09:21 UTC, Nibosi0501 commented on function/face.py
> +        cv.imwrite("dummy.jpg", output)
画像処理した写真は、./img/face_frame の中に保存されるようにパスを変更してください。

2024-01-07 09:21 UTC, Nibosi0501 commented on function/face.py
> +    file_name = "Lenna.png"
処理すべき画像は、 ./img の中に保存されるので、パスを変更してください。

2024-01-09 23:47 UTC, niwa100 commented on function/face.py
> +        cv.imwrite("dummy.jpg", output)
パスの部分を修正しました。

2024-01-09 23:48 UTC, niwa100 commented on function/face.py
> +    file_name = "Lenna.png"
パスの部分を修正しました。
これで合っていますか？

2024-01-10 11:16 UTC, yuutarougoto1102 commented on function/face.py
> +        cv.imwrite("dummy.jpg", output)
./img/face_frame/{任意のファイル名}.jpg　かも

2024-01-10 11:17 UTC, yuutarougoto1102 commented on function/face.py
> +        cv.imwrite("dummy.jpg", output)
合ってましたごめんなさい

2024-01-10 11:18 UTC, yuutarougoto1102 commented on function/face.py
> +    file_name = "Lenna.png"
合ってます！

2024-01-10 11:18 UTC, yutaro2481 commented
修正確認済みです！ありがとうございます。マージしときます。

2024-01-10 11:19 UTC, merged